/**
 * Custom Style Dictionary Output Formats
 *
 * Provides specialized formatters for:
 *   1. CSS Custom Properties (with OKLCH + rem) — two files: light + dark
 *   2. JSON (nested and flat)
 *   3. TypeScript const objects
 *   4. TypeScript declaration files
 *   5. Tailwind CSS theme extension
 *   6. Figma Tokens Studio JSON (round-trippable)
 */

// ─── Helper: camelCase converter ──────────────────────────────────────

function toCamelCase(str) {
  return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

// ─── Helper: CSS comment header ───────────────────────────────────────

function cssHeader(timestamp = new Date().toISOString()) {
  return `/* ═══════════════════════════════════════════════════════════════════
 * DESIGN TOKENS — Auto-generated by Style Dictionary
 * Generated: ${timestamp}
 * DO NOT EDIT MANUALLY.
 * Source: tokens/*.json → transforms → this file
 * ═══════════════════════════════════════════════════════════════════ */
`;
}

// ─── Helper: recursive token formatter ────────────────────────────────

function formatCSSVariable(path, value) {
  const name = `--${path.join('-')}`;
  return `  ${name}: ${value};`;
}

function formatDarkVariable(tokenPath, value) {
  // Map light semantic colors to their dark equivalents
  const darkMap = {
    'color-semantic-bg-base': 'var(--color-dark-bg-base)',
    'color-semantic-bg-subtle': 'var(--color-dark-bg-subtle)',
    'color-semantic-bg-muted': 'var(--color-dark-bg-muted)',
    'color-semantic-fg-base': 'var(--color-dark-fg-base)',
    'color-semantic-fg-muted': 'var(--color-dark-fg-muted)',
    'color-semantic-fg-subtle': 'var(--color-dark-fg-subtle)',
    'color-semantic-border-base': 'var(--color-dark-border-base)',
    'color-semantic-border-strong': 'var(--color-dark-border-strong)',
  };
  const key = tokenPath.join('-');
  if (darkMap[key]) return darkMap[key];
  return value;
}

// ─── Format 1: CSS Variables (Light Theme) ────────────────────────────

export function cssVariablesFormat({ dictionary, options }) {
  const header = options?.showFileHeader !== false
    ? cssHeader()
    : '';

  let output = `${header}
:root {
  /* ═══ Primitives: Colors ═══ */`;

  // Output all tokens, organized by their path prefix
  const byCategory = {};
  dictionary.allTokens.forEach((token) => {
    const cat = token.path[0];
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push(token);
  });

  const categoryLabels = {
    color: 'Colors',
    typography: 'Typography',
    spacing: 'Spacing',
    size: 'Sizing & Breakpoints',
    radius: 'Border Radius',
    shadow: 'Shadows',
    motion: 'Motion',
    zIndex: 'Z-Index',
  };

  for (const [cat, tokens] of Object.entries(byCategory)) {
    if (cat === 'dark') continue; // dark tokens go to separate file
    const label = categoryLabels[cat] || cat;
    output += `\n  /* ${label} */`;

    // Group by subcategory for colors
    if (cat === 'color' && tokens.some(t => t.path[1] === 'primitives')) {
      for (const token of tokens) {
        output += `\n${formatCSSVariable(token.path, token.value)}`;
      }
    } else {
      for (const token of tokens) {
        output += `\n${formatCSSVariable(token.path, token.value)}`;
      }
    }
  }

  output += '\n}\n';
  return output;
}

// ─── Format 2: CSS Variables (Dark Theme) ─────────────────────────────

export function cssVariablesDarkFormat({ dictionary, options }) {
  const header = options?.showFileHeader !== false
    ? cssHeader()
    : '';

  let output = `${header}
[data-theme="dark"],
.dark,
.dark-mode {
  /* ═══ Dark Theme Overrides ═══ */`;

  // Output dark tokens
  dictionary.allTokens.forEach((token) => {
    if (token.path.includes('dark')) {
      const darkPath = token.path;
      output += `\n${formatCSSVariable(darkPath, token.value)}`;
    }
  });

  // Also output semantic overrides mapping
  const semanticOverrides = {
    'color-semantic-bg-base': 'color-dark-bg-base',
    'color-semantic-bg-subtle': 'color-dark-bg-subtle',
    'color-semantic-bg-muted': 'color-dark-bg-muted',
    'color-semantic-fg-base': 'color-dark-fg-base',
    'color-semantic-fg-muted': 'color-dark-fg-muted',
    'color-semantic-fg-subtle': 'color-dark-fg-subtle',
    'color-semantic-fg-inverse': 'color-grey-950',
    'color-semantic-border-base': 'color-dark-border-base',
    'color-semantic-border-strong': 'color-dark-border-strong',
  };

  output += '\n\n  /* Semantic overrides → dark tokens */';
  for (const [semantic, darkRef] of Object.entries(semanticOverrides)) {
    const lightToken = dictionary.allTokens.find(
      t => t.path.join('-') === semantic
    );
    const darkToken = dictionary.allTokens.find(
      t => t.path.join('-') === darkRef
    );
    if (lightToken && darkToken) {
      output += `\n  --${semantic}: var(--${darkRef});`;
    }
  }

  // Shadow overrides for dark theme
  output += '\n\n  /* Dark shadows */';
  dictionary.allTokens.forEach((token) => {
    if (token.path.includes('dark')) {
      output += `\n${formatCSSVariable(token.path, token.value)}`;
    }
  });

  output += '\n}\n';
  return output;
}

// ─── Format 3: JSON Nested ────────────────────────────────────────────

export function jsonNestedFormat({ dictionary }) {
  const result = {};

  dictionary.allTokens.forEach((token) => {
    let current = result;
    const parts = token.path;
    for (let i = 0; i < parts.length - 1; i++) {
      if (!current[parts[i]]) current[parts[i]] = {};
      current = current[parts[i]];
    }
    const lastKey = parts[parts.length - 1];
    current[lastKey] = {
      value: token.value,
      type: token.type || 'string',
    };
    if (token.description) {
      current[lastKey].description = token.description;
    }
  });

  return JSON.stringify(result, null, 2);
}

// ─── Format 4: JSON Flat ──────────────────────────────────────────────

export function jsonFlatFormat({ dictionary }) {
  const result = {};

  dictionary.allTokens.forEach((token) => {
    const name = token.path.join('-');
    result[name] = token.value;
  });

  return JSON.stringify(result, null, 2);
}

// ─── Format 5: TypeScript Const Object ────────────────────────────────

export function typescriptConstFormat({ dictionary, options }) {
  const header = options?.showFileHeader !== false
    ? `/** ═══════════════════════════════════════════════════════════════════
 * DESIGN TOKENS — Auto-generated by Style Dictionary
 * Generated: ${new Date().toISOString()}
 * DO NOT EDIT MANUALLY.
 * ═══════════════════════════════════════════════════════════════════ */
`
    : '';

  let output = `${header}
export const tokens = {`;

  const byCategory = {};
  dictionary.allTokens.forEach((token) => {
    const cat = token.path[0];
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push(token);
  });

  for (const [category, tokens] of Object.entries(byCategory)) {
    output += `\n  /** ${category.charAt(0).toUpperCase() + category.slice(1)} tokens */`;
    output += `\n  ${toCamelCase(category)}: {`;

    for (const token of tokens) {
      const key = toCamelCase(token.path.slice(1).join('-'));
      const value = typeof token.value === 'string'
        ? `'${token.value.replace(/'/g, "\\'")}'`
        : token.value;
      output += `\n    ${key}: ${value},`;
    }

    output += `\n  },`;
  }

  output += '\n} as const;\n';
  return output;
}

// ─── Format 6: TypeScript Declaration File ────────────────────────────

export function typescriptTypesFormat({ dictionary, options }) {
  const header = options?.showFileHeader !== false
    ? `/** ═══════════════════════════════════════════════════════════════════
 * DESIGN TOKEN TYPES — Auto-generated by Style Dictionary
 * DO NOT EDIT MANUALLY.
 * ═══════════════════════════════════════════════════════════════════ */
`
    : '';

  let output = `${header}
declare const tokens: {`;

  const byCategory = {};
  dictionary.allTokens.forEach((token) => {
    const cat = token.path[0];
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push(token);
  });

  for (const [category, tokens] of Object.entries(byCategory)) {
    output += `\n  ${toCamelCase(category)}: {`;
    for (const token of tokens) {
      const key = toCamelCase(token.path.slice(1).join('-'));
      output += `\n    ${key}: string;`;
    }
    output += `\n  };`;
  }

  output += '\n};\n\nexport default tokens;\n';
  return output;
}

// ─── Format 7: Tailwind Theme Extension ───────────────────────────────

export function tailwindThemeFormat({ dictionary }) {
  const header = `/** ═══════════════════════════════════════════════════════════════════
 * TAILWIND THEME EXTENSION — Auto-generated from design tokens
 * Usage: import { tokens } from './design-tokens/tailwind'
 *        tailwind.config.theme.extend = tokens
 * ═══════════════════════════════════════════════════════════════════════ */
`;

  let output = `${header}
/** @type {import('tailwindcss').Config['theme']['extend']} */
export const tokens = {`;

  // Colors
  const colors = {};
  dictionary.allTokens
    .filter(t => t.path[0] === 'color' && !t.path.includes('dark'))
    .forEach((token) => {
      const colorPath = token.path.slice(1);
      let current = colors;
      for (let i = 0; i < colorPath.length - 1; i++) {
        if (!current[colorPath[i]]) current[colorPath[i]] = {};
        current = current[colorPath[i]];
      }
      current[colorPath[colorPath.length - 1]] = token.value;
    });

  if (Object.keys(colors).length > 0) {
    output += `\n  colors: ${JSON.stringify(colors, null, 4).replace(/"/g, "'")},`;
  }

  // Spacing
  const spacingTokens = dictionary.allTokens.filter(t => t.path[0] === 'spacing');
  if (spacingTokens.length > 0) {
    const spacing = {};
    spacingTokens.forEach(t => {
      spacing[t.path.slice(1).join('-')] = t.value;
    });
    output += `\n  spacing: ${JSON.stringify(spacing, null, 4).replace(/"/g, "'")},`;
  }

  // Font sizes
  const fontSizes = dictionary.allTokens.filter(t => t.path.includes('fontSize'));
  if (fontSizes.length > 0) {
    const sizes = {};
    fontSizes.forEach(t => {
      sizes[t.path[t.path.length - 1]] = [t.value, { lineHeight: '1.5' }];
    });
    output += `\n  fontSize: ${JSON.stringify(sizes, null, 4)},`;
  }

  // Font weights
  const fontWeights = dictionary.allTokens.filter(t => t.path.includes('fontWeight'));
  if (fontWeights.length > 0) {
    const weights = {};
    fontWeights.forEach(t => {
      weights[t.path[t.path.length - 1]] = String(t.value);
    });
    output += `\n  fontWeight: ${JSON.stringify(weights, null, 4).replace(/"/g, "'")},`;
  }

  // Border radius
  const radiusTokens = dictionary.allTokens.filter(t => t.path[0] === 'radius');
  if (radiusTokens.length > 0) {
    const radius = {};
    radiusTokens.forEach(t => {
      radius[t.path[t.path.length - 1]] = t.value;
    });
    output += `\n  borderRadius: ${JSON.stringify(radius, null, 4).replace(/"/g, "'")},`;
  }

  // Box shadow
  const shadowTokens = dictionary.allTokens.filter(t => t.path[0] === 'shadow' && t.path.includes('elevation'));
  if (shadowTokens.length > 0) {
    const shadows = {};
    shadowTokens.forEach(t => {
      shadows[t.path[t.path.length - 1]] = t.value;
    });
    output += `\n  boxShadow: ${JSON.stringify(shadows, null, 4).replace(/"/g, "'")},`;
  }

  output += '\n};\n';
  return output;
}

// ─── Format 8: Figma Tokens Studio JSON ───────────────────────────────

export function figmaTokensStudioFormat({ dictionary }) {
  /**
   * Output tokens in Figma Tokens Studio (formerly Figma Tokens plugin) format.
   * This allows round-tripping: Figma → JSON → Style Dictionary → JSON → Figma.
   *
   * Figma Tokens Studio format nests by sets/token groups.
   * Reference: https://docs.tokens.studio/
   */
  const result = {};

  dictionary.allTokens.forEach((token) => {
    const set = token.path[0] || 'global';
    if (!result[set]) result[set] = {};

    let current = result[set];
    const parts = token.path.slice(1); // skip category prefix
    for (let i = 0; i < parts.length - 1; i++) {
      if (!current[parts[i]]) current[parts[i]] = {};
      current = current[parts[i]];
    }

    const lastKey = parts[parts.length - 1];
    current[lastKey] = {
      value: token.original?.value || token.value,
      type: mapToFigmaType(token),
    };
    if (token.description) {
      current[lastKey].description = token.description;
    }
  });

  return JSON.stringify(result, null, 2);
}

function mapToFigmaType(token) {
  if (token.path[0] === 'color') return 'color';
  if (token.path.includes('fontSize') || token.path.includes('font-size')) return 'fontSizes';
  if (token.path.includes('fontWeight') || token.path.includes('font-weight')) return 'fontWeights';
  if (token.path.includes('lineHeight') || token.path.includes('line-height')) return 'lineHeights';
  if (token.path.includes('letterSpacing') || token.path.includes('letter-spacing')) return 'letterSpacing';
  if (token.path[0] === 'spacing') return 'spacing';
  if (token.path[0] === 'radius') return 'borderRadius';
  if (token.path[0] === 'shadow') return 'boxShadow';
  if (token.path[0] === 'motion' && token.path.includes('duration')) return 'duration';
  if (token.path[0] === 'motion' && token.path.includes('easing')) return 'cubicBezier';
  return 'other';
}

// ─── Register all formats ─────────────────────────────────────────────

export function registerFormats(StyleDictionary) {
  StyleDictionary.registerFormat({
    name: 'custom/css/variables',
    format: cssVariablesFormat,
  });

  StyleDictionary.registerFormat({
    name: 'custom/css/variables-dark',
    format: cssVariablesDarkFormat,
  });

  StyleDictionary.registerFormat({
    name: 'custom/json/nested',
    format: jsonNestedFormat,
  });

  StyleDictionary.registerFormat({
    name: 'custom/json/flat',
    format: jsonFlatFormat,
  });

  StyleDictionary.registerFormat({
    name: 'custom/typescript/const',
    format: typescriptConstFormat,
  });

  StyleDictionary.registerFormat({
    name: 'custom/typescript/types',
    format: typescriptTypesFormat,
  });

  StyleDictionary.registerFormat({
    name: 'custom/tailwind/theme',
    format: tailwindThemeFormat,
  });

  StyleDictionary.registerFormat({
    name: 'custom/figma/tokens-studio',
    format: figmaTokensStudioFormat,
  });
}
